DROP DATABASE IF EXISTS techblog_db;
CREATE DATABASE techblog_db;

CREATE TABLE user (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) Null DEFAULT NULL,
    email VARCHAR(50) NULL DEFAULT NULL,
    password VARCHAR(50) NOT NULL,

)



CREATE TABLE post (
id INTEGER NOT NULL AUTO_INCREMENT,
title VARCHAR(50) NOT NULL,
content TEXT NOT NULL,
user_id INTEGER NOT NULL,
)